// Generated by lib/quick-search/generate.mjs — do not edit by hand.
// Re-run `npm run quick-search` after adding or renaming a page.

import type { QuickSearchItem } from "./types";

/** Every linkable page in the App Router tree, grouped by where it lives. */
export const ROUTE_ITEMS: QuickSearchItem[] = [
	{
		id: "home",
		title: "Home",
		href: "/",
		group: "Pages",
		keywords: ["landing","overview","start"],
		hint: "/",
	},
	{
		id: "about",
		title: "About",
		href: "/about",
		group: "Pages",
		hint: "/about",
	},
	{
		id: "careers",
		title: "Careers",
		href: "/careers",
		group: "Pages",
		hint: "/careers",
	},
	{
		id: "contact",
		title: "Contact",
		href: "/contact",
		group: "Pages",
		hint: "/contact",
	},
	{
		id: "dashboard",
		title: "Dashboard",
		href: "/dashboard",
		group: "Pages",
		hint: "/dashboard",
	},
	{
		id: "privacy",
		title: "Privacy",
		href: "/privacy",
		group: "Pages",
		hint: "/privacy",
	},
	{
		id: "team",
		title: "Team",
		href: "/team",
		group: "Pages",
		hint: "/team",
	},
	{
		id: "terms",
		title: "Terms",
		href: "/terms",
		group: "Pages",
		hint: "/terms",
	},
	{
		id: "apps-bumboo-privacy",
		title: "Privacy",
		href: "/apps/bumboo/privacy",
		group: "Apps · Bumboo",
		keywords: ["apps","bumboo"],
		hint: "/apps/bumboo/privacy",
	},
	{
		id: "apps-pitchplease-privacy",
		title: "Privacy",
		href: "/apps/pitchplease/privacy",
		group: "Apps · Pitchplease",
		keywords: ["apps","pitchplease"],
		hint: "/apps/pitchplease/privacy",
	},
	{
		id: "apps-screenful-privacy",
		title: "Privacy",
		href: "/apps/screenful/privacy",
		group: "Apps · Screenful",
		keywords: ["apps","screenful"],
		hint: "/apps/screenful/privacy",
	},
];
